# Setup data dir 2
- name: Create Data 2 Directory
  file: 
    path: /opt/data_2
    recurse: yes
    state: directory 
    mode: 0755
    owner: 0
    group: 0
  become: yes

- name: Create Data 2 Partition
  community.general.parted:
    device: /dev/vdc
    number: 1
    state: present
    fs_type: ext4
    label: gpt
  become: yes

- name: Create a ext4 filesystem on /dev/vdc1
  community.general.filesystem:
    fstype: ext4 
    dev: /dev/vdc1
    state: present
  become: yes

- name: Mount As /opt/data_2
  ansible.posix.mount:
    path: /opt/data_2
    src: /dev/vdc1
    fstype: ext4
    state: mounted
  become: yes